version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: build-all-platforms
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds:
      - build-all-platforms
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: leandrodaf
    name: Pianalyze

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
