sonar.organization=leandrodaf
sonar.projectKey=leandrodaf_pianalyze

sonar.sources=cmd,internal,frontend/src
sonar.tests=cmd,internal,frontend/src
sonar.test.inclusions=**/*_test.go,frontend/src/**/*.test.ts,frontend/src/**/*.spec.ts
sonar.exclusions=frontend/src/lib/i18n/locales/**,frontend/dist/**

sonar.go.coverage.reportPaths=coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
