// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {grading} from '../models';

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function LoadPracticeIntervals(arg1:Array<grading.Interval>):Promise<void>;

export function PausePractice(arg1:number):Promise<void>;

export function SaveRecording(arg1:string):Promise<void>;

export function SelectDevice(arg1:number):Promise<void>;

export function StartCapture():Promise<void>;

export function StartPractice(arg1:number,arg2:number):Promise<void>;

export function StartRecording():Promise<void>;

export function StopCapture():Promise<void>;

export function StopPractice():Promise<void>;

export function StopRecording():Promise<string>;
