// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function SelectDevice(arg1) {
  return window['go']['main']['App']['SelectDevice'](arg1);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
