// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {grading} from '../models';

export function AutoSaveRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDefaultSavePath():Promise<string>;

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function LoadGradingProfile(arg1:grading.Profile):Promise<void>;

export function LoadPracticeIntervals(arg1:Array<grading.Interval>):Promise<void>;

export function LoadRecordingFile():Promise<string>;

export function PausePractice(arg1:number):Promise<void>;

export function PauseRecording():Promise<void>;

export function PickSaveDirectory(arg1:string):Promise<string>;

export function ResumeRecording():Promise<void>;

export function SaveRecording(arg1:string):Promise<void>;

export function SelectDevice(arg1:number):Promise<void>;

export function StartCapture():Promise<void>;

export function StartPractice(arg1:number,arg2:number):Promise<void>;

export function StartRecording():Promise<void>;

export function StopCapture():Promise<void>;

export function StopPractice():Promise<void>;

export function StopRecording():Promise<string>;
