// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {grading} from '../models';

export function AutoSaveRecording(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteRecording(arg1:string):Promise<void>;

export function GetDefaultSavePath():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportAnyFile():Promise<main.ImportResult>;

export function ImportScoreFile():Promise<string>;

export function ListBuiltinLibrary():Promise<Array<main.RecordingSummary>>;

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function ListRecordings(arg1:string):Promise<Array<main.RecordingSummary>>;

export function LoadBuiltinPiece(arg1:string):Promise<string>;

export function LoadGradingProfile(arg1:grading.Profile):Promise<void>;

export function LoadPracticeIntervals(arg1:Array<grading.Interval>):Promise<void>;

export function LoadRecordingFile():Promise<string>;

export function OpenRecordingFolder(arg1:string):Promise<void>;

export function PausePractice(arg1:number):Promise<void>;

export function PauseRecording():Promise<void>;

export function PickSaveDirectory(arg1:string):Promise<string>;

export function ReadRecordingByPath(arg1:string):Promise<string>;

export function ReportError(arg1:string,arg2:string):Promise<void>;

export function ResumeRecording():Promise<void>;

export function SaveRecording(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectDevice(arg1:number):Promise<void>;

export function StartCapture():Promise<void>;

export function StartPractice(arg1:number,arg2:number):Promise<void>;

export function StartRecording():Promise<void>;

export function StopCapture():Promise<void>;

export function StopPractice():Promise<void>;

export function StopRecording():Promise<string>;

export function SyncMenuState(arg1:main.MenuState):Promise<void>;

export function UpdateRecordingMeta(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
